### ISSUE TITLE
Ruby library slack message not accepted

### ISSUE THREAD

**Issue by poVoq** [jlu5/Limnoria-Grapnel#1]
See discussion here:

https://github.com/loomio/loomio/issues/10111

I need to look deeper into the issue, but it seems to me that the send json is not correctly parsed on the Grapnel side.

Any idea?

**Comment by jlu5** [comment]
Do you have debug logs (`config log.level DEBUG`) from your bot when you try to receive a payload? The text snippets posted on that issue look fine to me.

**Comment by poVoq** [comment]
In the Limnoria logs there is only a 400 error response visible, even at DEBUG level.

But from the error response on the loomio side, it says: `400 bad request; Bad HTTP Content-Type (expected JSON)`

Edit: it further says something about reading bytes and "\r\n" and "0\r\n" and another "\r\n" which looks to me like it might referred to escaped characters withing the webhook "text" payload like mentioned in the linked issue on the Loomio issue tracker.

Edit: sorry having issues logging into github from my desktop, here is the full response error from loomio:
https://docs.slrpnk.net/s/cbvft7f5y3pkgapcv2q7aj8dh8

**Comment by poVoq** [comment]
Seems to work now with Loomio. Thanks a lot!

**Comment by poVoq** [comment]
Actually the test connection button works, but webhooks triggered by actual forum posts don't seem to work yet. Strange.

**Comment by poVoq** [comment]
Looks like after the last multi-line improvements this now finally works with Loomio.
